'use client';
import {useEffect,useState} from 'react';
import {supabaseBrowser} from '../../lib/supabase';
import {useRouter} from 'next/navigation';

export default function Admin(){
 const s=supabaseBrowser(),router=useRouter();
 const [p,setP]=useState<any>(),[students,setStudents]=useState<any[]>([]),[regs,setRegs]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[assignments,setAssignments]=useState<any[]>([]),[coursesDb,setCoursesDb]=useState<any[]>([]),[submissions,setSubmissions]=useState<any[]>([]),[attendance,setAttendance]=useState<any[]>([]);
 const [q,setQ]=useState(''),[tab,setTab]=useState('students'),[notice,setNotice]=useState(''),[selectedStudent,setSelectedStudent]=useState<any>();
 const [classForm,setClassForm]=useState<any>({title:'',course_id:'',starts_at:'',duration_minutes:90,meet_url:'',week:1,facilitator:''});
 const [assignmentForm,setAssignmentForm]=useState<any>({title:'',course_id:'',instructions:'',due_at:'',max_score:100,week:1});
 async function load(){
  const {data:u}=await s.auth.getUser();if(!u.user)return router.push('/login');
  const {data:prof}=await s.from('profiles').select('*').eq('id',u.user.id).single();if(prof?.role!=='admin')return router.push('/dashboard');setP(prof);
  const [a,b,c,d,e,f,g]=await Promise.all([s.from('profiles').select('*').order('created_at',{ascending:false}),s.from('registrations').select('*').order('created_at',{ascending:false}),s.from('classes').select('*,courses(name)').order('starts_at'),s.from('assignments').select('*,courses(name)').order('due_at'),s.from('courses').select('*').order('name'),s.from('submissions').select('*,assignments(title,max_score,week,courses(name))').order('submitted_at',{ascending:false}),s.from('attendance').select('*,classes(title,starts_at,week,courses(name))')]);
  setStudents(a.data||[]);setRegs(b.data||[]);setClasses(c.data||[]);setAssignments(d.data||[]);setCoursesDb(e.data||[]);setSubmissions(f.data||[]);setAttendance(g.data||[]);
 }
 useEffect(()=>{load()},[]);
 const filtered=students.filter(x=>(x.full_name+' '+x.email).toLowerCase().includes(q.toLowerCase()));
 async function makeAdmin(id:string){await s.from('profiles').update({role:'admin'}).eq('id',id);setNotice('Admin access granted.');load()}
 async function addClass(e:any){e.preventDefault();const {error}=await s.from('classes').insert({...classForm,duration_minutes:Number(classForm.duration_minutes),week:Number(classForm.week)});setNotice(error?.message||'Class created.');if(!error){setClassForm({title:'',course_id:'',starts_at:'',duration_minutes:90,meet_url:'',week:1,facilitator:''});load()}}
 async function addAssignment(e:any){e.preventDefault();const {error}=await s.from('assignments').insert({...assignmentForm,max_score:Number(assignmentForm.max_score),week:Number(assignmentForm.week)});setNotice(error?.message||'Assignment created.');if(!error){setAssignmentForm({title:'',course_id:'',instructions:'',due_at:'',max_score:100,week:1});load()}}
 async function grade(id:string,score:any,feedback:string){const {data:u}=await s.auth.getUser();const {error}=await s.from('submissions').update({score:Number(score),feedback,status:'graded',reviewed_by:u.user?.id,reviewed_at:new Date().toISOString()}).eq('id',id);setNotice(error?.message||'Submission graded.');if(!error)load()}
 async function markAttendance(classId:string,studentId:string,status:string){const {error}=await s.from('attendance').upsert({class_id:classId,student_id:studentId,status},{onConflict:'class_id,student_id'});setNotice(error?.message||'Attendance saved.');if(!error)load()}
 function exportRows(rows:any[],headers:string[],name:string){const csv=[headers,...rows].map(r=>r.map((v:any)=>String.fromCharCode(34)+String(v??'').replaceAll(String.fromCharCode(34),String.fromCharCode(34)+String.fromCharCode(34))+String.fromCharCode(34)).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name;a.click()}
 function studentRecord(id:string){return {subs:submissions.filter(x=>x.student_id===id),att:attendance.filter(x=>x.student_id===id)}}
 if(!p)return <main className="login"><div className="loginbox center">Loading admin console…</div></main>;
 return <div><header className="topbar"><div className="brand"><div className="mark">OAF</div>Oladunni Art Fellowship <span className="pill red">ADMIN</span></div><button className="btn ghost" onClick={async()=>{await s.auth.signOut();router.push('/')}}>Sign out</button></header>
 <aside className="side">{[['students','Students'],['records','Records'],['registrations','Applications'],['classes','Classes'],['assignments','Assignments'],['programme','Programme']].map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}</aside>
 <main className="main"><p className="eyebrow">Control centre</p><h1 className="h1">Good morning, Fikayo.</h1><p className="sub">Manage the fellowship from one professional workspace.</p>{notice&&<div className="card" style={{marginTop:16,borderColor:'var(--red)'}}>{notice}</div>}
 <div className="grid g4" style={{marginTop:24}}>{[['Students',students.length],['Applications',regs.length],['Classes',classes.length],['Submissions',submissions.length]].map(x=><div className="card" key={String(x[0])}><div className="label">{x[0]}</div><div className="metric">{x[1]}</div></div>)}</div>
 {tab==='students'&&<section className="card" style={{marginTop:28}}><div className="split"><div><p className="eyebrow">Student directory</p><h2>Search track records</h2></div><div className="actions"><input placeholder="Search name or email…" value={q} onChange={e=>setQ(e.target.value)} style={{padding:11,border:'1px solid #ddd',borderRadius:9}}/><button className="btn dark" onClick={()=>exportRows(filtered.map(x=>[x.full_name,x.email,x.role,x.phone||'',x.cohort||'']),['Name','Email','Role','Phone','Cohort'],'oaf-students.csv')}>Export</button></div></div><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Cohort</th><th>Action</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{x.full_name||'Unnamed fellow'}</b></td><td>{x.email}</td><td><span className="pill">{x.role}</span></td><td>{x.cohort||'—'}</td><td><button className="btn ghost" onClick={()=>{setSelectedStudent(x);setTab('records')}}>Open record</button>{x.role!=='admin'&&<button className="btn ghost" onClick={()=>makeAdmin(x.id)}>Make admin</button>}</td></tr>)}</tbody></table></div></section>}
 {tab==='records'&&<section className="card" style={{marginTop:28}}><div className="split"><div><p className="eyebrow">Academic record centre</p><h2>{selectedStudent?selectedStudent.full_name:'Select a fellow'}</h2></div>{selectedStudent&&<button className="btn dark" onClick={()=>{const r=studentRecord(selectedStudent.id);exportRows([...r.subs.map(x=>['Assignment',x.assignments?.title,x.status,x.score??'',x.feedback||'']),...r.att.map(x=>['Attendance',x.classes?.title,x.status,new Date(x.classes?.starts_at).toLocaleDateString(),x.classes?.courses?.name||''])],['Type','Item','Status','Score/Date','Feedback/Course'],'oaf-'+selectedStudent.full_name.replace(/\s+/g,'-')+'.csv')}}>Export full record</button>}</div>{!selectedStudent?<p className="sub">Open a student from the Students tab to view their 12-week record.</p>:<><div className="grid g4" style={{marginTop:18}}>{(()=>{const r=studentRecord(selectedStudent.id);return [['Submissions',r.subs.length],['Graded',r.subs.filter(x=>x.status==='graded').length],['Present/Late',r.att.filter(x=>['present','late'].includes(x.status)).length],['Absences',r.att.filter(x=>x.status==='absent').length]].map(x=><div className="card" key={String(x[0])}><div className="label">{x[0]}</div><div className="metric">{x[1]}</div></div>)})()}</div><h3 style={{marginTop:28}}>Submissions & grading</h3><table className="table"><thead><tr><th>Week</th><th>Assignment</th><th>Status</th><th>Score</th><th>Feedback</th><th>Action</th></tr></thead><tbody>{studentRecord(selectedStudent.id).subs.map(x=><tr key={x.id}><td>{x.assignments?.week||'—'}</td><td>{x.assignments?.title}</td><td>{x.status}</td><td><input defaultValue={x.score??''} id={'score-'+x.id} style={{width:70}}/></td><td><input defaultValue={x.feedback||''} id={'feedback-'+x.id} style={{width:220}}/></td><td><button className="btn primary" onClick={()=>grade(x.id,(document.getElementById('score-'+x.id) as HTMLInputElement)?.value,(document.getElementById('feedback-'+x.id) as HTMLInputElement)?.value)}>Save grade</button></td></tr>)}</tbody></table><h3 style={{marginTop:28}}>12-week attendance</h3><table className="table"><thead><tr><th>Week</th><th>Class</th><th>Course</th><th>Date</th><th>Status</th></tr></thead><tbody>{studentRecord(selectedStudent.id).att.map(x=><tr key={x.id}><td>{x.classes?.week}</td><td>{x.classes?.title}</td><td>{x.classes?.courses?.name}</td><td>{x.classes?.starts_at?new Date(x.classes.starts_at).toLocaleDateString():'—'}</td><td><select value={x.status} onChange={e=>markAttendance(x.class_id,x.student_id,e.target.value)}><option>present</option><option>late</option><option>absent</option><option>excused</option></select></td></tr>)}</tbody></table></>}</section>}
 {tab==='registrations'&&<section className="card" style={{marginTop:28}}><div className="split"><div><p className="eyebrow">Admissions</p><h2>Fellowship applications</h2></div><button className="btn dark" onClick={()=>exportRows(regs.map(x=>[x.full_name,x.email,x.phone||'',x.age||'',x.city||'',(x.selected_courses||[]).join('; '),x.status]),['Name','Email','Phone','Age','City','Courses','Status'],'oaf-applications.csv')}>Export applications</button></div><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Name</th><th>Email</th><th>Courses</th><th>Age</th><th>City</th><th>Status</th></tr></thead><tbody>{regs.map(x=><tr key={x.id}><td>{x.full_name}</td><td>{x.email}</td><td>{(x.selected_courses||[]).join(', ')}</td><td>{x.age||'—'}</td><td>{x.city||'—'}</td><td><span className="pill">{x.status}</span></td></tr>)}</tbody></table></div></section>}
 {tab==='classes'&&<section style={{marginTop:28}} className="grid g3"><div className="card"><p className="eyebrow">Schedule</p><h2>Create live class</h2><form className="form" onSubmit={addClass}><input placeholder="Class title" required value={classForm.title} onChange={e=>setClassForm({...classForm,title:e.target.value})}/><select required value={classForm.course_id} onChange={e=>setClassForm({...classForm,course_id:e.target.value})}><option value="">Choose course</option>{coursesDb.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="datetime-local" required onChange={e=>setClassForm({...classForm,starts_at:new Date(e.target.value).toISOString()})}/><input placeholder="Google Meet link" value={classForm.meet_url} onChange={e=>setClassForm({...classForm,meet_url:e.target.value})}/><input placeholder="Facilitator" value={classForm.facilitator} onChange={e=>setClassForm({...classForm,facilitator:e.target.value})}/><input type="number" min="1" max="12" placeholder="Week" value={classForm.week} onChange={e=>setClassForm({...classForm,week:e.target.value})}/><button className="btn primary">Create class</button></form></div><div className="card" style={{gridColumn:'span 2'}}><p className="eyebrow">Upcoming</p><h2>Live classes</h2><table className="table"><thead><tr><th>Class</th><th>Course</th><th>Week</th><th>Starts</th><th>Meet</th></tr></thead><tbody>{classes.map(x=><tr key={x.id}><td>{x.title}</td><td>{x.courses?.name}</td><td>{x.week}</td><td>{new Date(x.starts_at).toLocaleString()}</td><td>{x.meet_url?<a href={x.meet_url} target="_blank">Open Meet</a>:'—'}</td></tr>)}</tbody></table></div></section>}
 {tab==='assignments'&&<section style={{marginTop:28}} className="grid g3"><div className="card"><p className="eyebrow">Assessment</p><h2>Create assignment</h2><form className="form" onSubmit={addAssignment}><input placeholder="Assignment title" required value={assignmentForm.title} onChange={e=>setAssignmentForm({...assignmentForm,title:e.target.value})}/><select required value={assignmentForm.course_id} onChange={e=>setAssignmentForm({...assignmentForm,course_id:e.target.value})}><option value="">Choose course</option>{coursesDb.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea rows={5} placeholder="Instructions" value={assignmentForm.instructions} onChange={e=>setAssignmentForm({...assignmentForm,instructions:e.target.value})}/><input type="datetime-local" onChange={e=>setAssignmentForm({...assignmentForm,due_at:e.target.value?new Date(e.target.value).toISOString():null})}/><input type="number" placeholder="Maximum score" value={assignmentForm.max_score} onChange={e=>setAssignmentForm({...assignmentForm,max_score:e.target.value})}/><input type="number" min="1" max="12" placeholder="Week" value={assignmentForm.week} onChange={e=>setAssignmentForm({...assignmentForm,week:e.target.value})}/><button className="btn primary">Create assignment</button></form></div><div className="card" style={{gridColumn:'span 2'}}><p className="eyebrow">Assessment list</p><h2>Assignments</h2><table className="table"><thead><tr><th>Title</th><th>Course</th><th>Week</th><th>Due</th><th>Score</th></tr></thead><tbody>{assignments.map(x=><tr key={x.id}><td>{x.title}</td><td>{x.courses?.name}</td><td>{x.week}</td><td>{x.due_at?new Date(x.due_at).toLocaleString():'No deadline'}</td><td>{x.max_score}</td></tr>)}</tbody></table></div></section>}
 {tab==='programme'&&<section style={{marginTop:28}} className="card"><p className="eyebrow">OAF curriculum</p><h2>Three-month creative development programme</h2><p className="sub">Six tracks: Scriptwriting, Acting, Film Production, Film Directing, Film Editing and Film Distribution.</p><div className="grid g3" style={{marginTop:18}}>{coursesDb.map((c,i)=><div className="card" key={c.id}><span className="pill red">0{i+1}</span><h3>{c.name}</h3><p className="sub">{c.description}</p></div>)}</div></section>}
 </main></div>
}